package com.amarjeetmaan.ajbroadcaster.overlay

/**
 * Events generated by the overlay subsystem.
 */
sealed class OverlayEvent {

    /**
     * Overlay became visible.
     */
    data class Shown(
        val overlayId: String
    ) : OverlayEvent()

    /**
     * Overlay became hidden.
     */
    data class Hidden(
        val overlayId: String
    ) : OverlayEvent()

    /**
     * Overlay data changed.
     */
    data class Updated(
        val overlayId: String
    ) : OverlayEvent()

    /**
     * Overlay entered animation.
     */
    data class AnimationStarted(
        val overlayId: String,
        val animation: String,
        val direction: String
    ) : OverlayEvent()

    /**
     * Overlay animation completed.
     */
    data class AnimationFinished(
        val overlayId: String,
        val animation: String
    ) : OverlayEvent()

    /**
     * Overlay rendering failed.
     */
    data class RenderFailed(
        val overlayId: String,
        val message: String
    ) : OverlayEvent()

    /**
     * Overlay queue changed.
     */
    data class QueueChanged(
        val size: Int
    ) : OverlayEvent()

    /**
     * Layer order changed.
     */
    data class LayerChanged(
        val overlayId: String,
        val zIndex: Int
    ) : OverlayEvent()

    /**
     * Complete overlay system cleared.
     */
    data object Cleared : OverlayEvent()
}
